/* =====================================================
   ARCHIVO: menu.js
   FUNCIÓN: Manejar los datos del menú y su renderizado
   ===================================================== */

/* -----------------------------------------------------
   1. DATOS DEL MENÚ
   -----------------------------------------------------
   Cada objeto representa UN producto del restaurante.
   Las categorías deben coincidir EXACTAMENTE con las
   categorías técnicas definidas en el HTML.
----------------------------------------------------- */
console.log("menu.js cargado correctamente");

const menuItems = [
  {
    nombre: "Arroz",
    descripcion: "Plato con porcion de arroz.",
    precio: 4000,
    categoria: "porciones", 
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901503/arroz_owvvnm.jpg",
  },
  {
    nombre: "Aguacate",
    descripcion: "Plato con porcion de aguacate.",
    precio: 5800,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901503/aguacate_pfyszu.jpg",
  },
  {
    nombre: "Huevo",
    descripcion: "Plato con porción de huevo frito.",
    precio: 4300,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901514/huevos_pvilag.jpg",
  },
  {
    nombre: "Limon",
    descripcion: "Plato porcionado con limón picado.",
    precio: 2500,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901513/limon_bbosfj.jpg",
  },
  {
    nombre: "Ensalada dulce",
    descripcion: "Producto adicional de piña, guanabana, gelatina, crema chantilly y perlitas de sabores.",
    precio: 14000,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767934546/ensaladadulce_k1ymul.jpg",
  },
  {
    nombre: "Ensalada dulce - pequeña",
    descripcion: "Producto adicional de piña, guanabana, gelatina, crema chantilly y perlitas de sabores, en menor tamaño",
    precio: 8000,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901506/ensaladadulcepequenajpg_ahm80k.jpg",
  },
  {
    nombre: "Ensalada - verduras",
    descripcion: "Ensalada hecha a partir de tomate, cebolla, limon, y pepino.",
    precio: 8500,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901508/ensaladaverduras_ohbhax.jpg",
  },
  {
    nombre: "Entrada - trifasico, mondongo o pescado",
    descripcion: "Porción de sancocho trifásico, sancocho de pescado o mondongo.",
    precio: 20000,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901512/entradasopa_jyigje.jpg",
  },
  {
    nombre: "Frijoles",
    descripcion: "Porcion de frijoles.",
    precio: 17000,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901514/frijoles_qsns8s.jpg",
  },
  {
    nombre: "Sopa del dia",
    descripcion: "Plato con sancocho trifásico, sancocho de pescado o mondongo de menor tamaño.",
    precio: 13500,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901527/sopadeldia_vqchaq.jpg",
  },
  {
    nombre: "Porcion de patacon",
    descripcion: "Porcion de entrada hecha de patacón y hogao.",
    precio: 2800,
    categoria: "porciones",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901524/patacon_psmuad.jpg",
  },
  {
    nombre: "Seviche de chicarron",
    descripcion: "Crujiente chicharrón picado, marinado con limón, cebolla, tomate y toques frescos de la casa.",
    precio: 29000,
    categoria: "platos para picar",
    imagen: "productos_imagenes/comidas/seviche.jpg",
  },
  {
    nombre: "Plato con costillas",
    descripcion: "Costillas de cerdo doradas y jugosas, acompañadas de papas a la francesa, arepa y ensalada fresca.",
    precio: 29000,
    categoria: "platos para picar",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901503/costillasbbq_gzwidj.jpg",
  },
  {
    nombre: "Plato con chicharron",
    descripcion: "Chicharrón crocante servido con papas a la francesa, arepa y ensalada de la casa.",
    precio: 29000,
    categoria: "platos para picar",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901503/costillasbbq_gzwidj.jpg",
  },
  {
    nombre: "Arepaburger",
    descripcion: "Arepaburger artesanal servida con queso, papas a la francesa y acompañamientos.",
    precio: 29000,
    categoria: "platos para picar",
    imagen: "productos_imagenes/comidas/arepaburger.jpg",
  },
  {
    nombre: "Plato con chorizos",
    descripcion: "Chorizos asados al punto perfecto, acompañados de papas a la francesa, arepa y ensalada fresca.",
    precio: 29000,
    categoria: "platos para picar",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767973063/platochorizos_ux1dbr.jpg",
  },
  {
    nombre: "Chuzo",
    descripcion: "Chuzo de carne de cero o pollo a la parrilla, jugoso y bien sazonado, acompañado de papas, arepa y salsas.",
    precio: 29000,
    categoria: "platos para picar",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901505/chuzocerdo_ov07ys.jpg",
  },
  {
    nombre: "Empanadas",
    descripcion: "Empanadas fritas y crujientes, rellenas de carne y papa, servidas con limón y ají.",
    precio: 2500,
    categoria: "platos para picar",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901506/empanadas_wvno9n.jpg",
  },
  {
    nombre: "Choripapa",
    descripcion: "Chorizo asado con papas a la francesa, salsas tradicionales.",
    precio: 23000,
    categoria: "platos para picar",
    imagen: "productos_imagenes/comidas/choripapa.jpg",
  },
  {
    nombre: "Papas a la francesa",
    descripcion: "Papas fritas doradas y crujientes, ideales para compartir o acompañar cualquier plato.",
    precio: 18000,
    categoria: "platos para picar",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901522/papasfrancesa_gtdhl8.jpg",
  },
  {
    nombre: "Bandeja paisa",
    descripcion: "Plato típico colombiano con fríjoles, arroz, chicharrón, carne molida, huevo, plátano maduro, arepa y aguacate.",
    precio: 40000,
    categoria: "platos del dia",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901506/bandejapaisa_upqvsz.jpg",
  },
  {
    nombre: "Lomo dorado",
    descripcion: "Lomo de cerdo dorado y jugoso, acompañado de papas a la francesa, arepa y ensalada fresca.",
    precio: 40000,
    categoria: "platos del dia",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901518/lomodorado_mfo4li.jpg",
  },
  {
    nombre: "Pechuga dorada",
    descripcion: "Pechuga de pollo a la plancha, dorada al punto perfecto, servida con papas, arepa y ensalada.",
    precio: 40000,
    categoria: "platos del dia",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901525/pechugadorada_vyal0t.jpg",
  },
  {
    nombre: "Milanesa de cerdo",
    descripcion: "Milanesa de cerdo empanizada y crujiente, acompañada de papas a la francesa y ensalada fresca.",
    precio: 40000,
    categoria: "platos del dia",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901523/milanesa_dxrg2u.jpg",
  },
  {
    nombre: "Milanesa de pollo",
    descripcion: "Filete de pollo empanizado y crocante, servido con papas a la francesa y ensalada.",
    precio: 40000,
    categoria: "platos del dia",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767977092/milanesapollo_olpwg8.jpg",
  },
  {
    nombre: "Plato mixto",
    descripcion: "Combinación de carnes a la parrilla, acompañadas de papas a la francesa, arepa y ensalada.",
    precio: 40000,
    categoria: "platos del dia",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767977202/platomixto_ihibap.jpg",
  },
  {
    nombre: "Cazuela de frijol",
    descripcion: "Cazuela tradicional de fríjoles con arroz, carne, chicharrón, arepa y acompañamientos de la casa.",
    precio: 40000,
    categoria: "platos del dia",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901504/cazueladefrijoles_ujo5b4.jpg",
  },
  {
    nombre: "Lomo de res",
    descripcion: "Lomo de res a la parrilla, jugoso y bien sazonado, servido con papas, arepa y ensalada.",
    precio: 40000,
    categoria: "platos del dia",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901518/lomores_aleyh0.jpg",
  },
  {
    nombre: "Churrasco",
    descripcion: "Corte de res a la parrilla, jugoso y bien asado, acompañado de papas al vapor, arepa y ensalada fresca.",
    precio: 62000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901505/churrasco_i00fyf.jpg",
  },
  {
    nombre: "Lomito biche",
    descripcion: "Lomito de res tierno y jugoso, servido con papas a la francesa, arepa y acompañamientos de la casa.",
    precio: 60000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901518/lomitobiche_yin3id.jpg",
  },
  {
    nombre: "Mojarra frita",
    descripcion: "Mojarra entera frita y crocante, acompañada de papas a la francesa, patacón, arepa y ensalada.",
    precio: 60000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901522/mojarrafrita_bczrft.jpg",
  },
  {
    nombre: "Lengua dorada",
    descripcion: "Lengua dorada a la plancha, suave y llena de sabor, servida con papas, arepa y ensalada.",
    precio: 60000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901514/lenguadorada_qpckfv.jpg",
  },
  {
    nombre: "Lengua en salsa criolla",
    descripcion: "Lengua bañada en salsa criolla tradicional, acompañada de arroz, papa y ensalada fresca.",
    precio: 60000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901513/lenguasalsacriolla_tclebm.jpg",
  },
  {
    nombre: "Sobrebarriga dorada",
    descripcion: "Sobrebarriga dorada a la plancha, jugosa y bien sazonada, servida con papas, arepa y ensalada.",
    precio: 60000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767974714/sobrebarrigadorada_uejd5e.jpg",
  },
  {
    nombre: "Sobrebarriga en salsa criolla",
    descripcion: "Sobrebarriga suave y jugosa, cocinada en salsa criolla, acompañada de arroz, papa y ensalada.",
    precio: 60000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901527/sobrebarrigasalsacriolla_ym9iva.jpg",
  },
  {
    nombre: "Salmon a la marinera",
    descripcion: "Filete de salmón en salsa marinera, servido con papas a la francesa, arroz y ensalada fresca.",
    precio: 62000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767974853/salmonmarinera_jov3w7.jpg",
  },
  {
    nombre: "Trucha a la plancha",
    descripcion: "Trucha fresca a la plancha, dorada al punto perfecto, acompañada de papas, arepa y ensalada.",
    precio: 62000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901528/truchaplancha_jfvxvp.jpg",
  },
  {
    nombre: "Trucha a la marinera",
    descripcion: "Filete de trucha en salsa marinera, servido con papas a la francesa, arroz y ensalada fresca.",
    precio: 62000,
    categoria: "platos a la carta",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901527/truchamarinera_t1ei5q.jpg",
  },
  {
    nombre: "Plato ejecutivo",
    descripcion: "Plato completo con arroz, papas a la francesa, ensalada fresca y acompañamientos de la casa, con proteína a elección: Lomo de res, lomo de cerdo, pechuga dorada, milanesa de cerdo o milanesa de pollo.",
    precio: 29000,
    categoria: "menu ejecutivo",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901507/ejecutivo_vheteu.jpg",
  },
  {
    nombre: "Lomo de cerdo dorado con queso y tocineta",
    descripcion: "Lomo de cerdo dorado a la plancha, cubierto con queso fundido y tocineta crocante, acompañado de papas, arepa y ensalada.",
    precio: 45000,
    categoria: "opcional-carnes",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901518/lomodoradoqyt_fmsh1s.jpg",
  },
  {
    nombre: "Lomito fino de res con queso y tocineta",
    descripcion: "Lomito de res tierno y jugoso, gratinado con queso y tocineta crocante, servido con papas, arepa y ensalada fresca.",
    precio: 45000,
    categoria: "opcional-carnes",
    imagen: "productos_imagenes/comidas/solomoqyt.jpg",
  },
  {
    nombre: "Pechuga dorada con queso y tocineta",
    descripcion: "Pechuga de pollo dorada al punto perfecto, con queso fundido y tocineta crocante, acompañada de papas, arepa y ensalada.",
    precio: 45000,
    categoria: "opcional-carnes",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901525/pechugadoradaqyt_jxppdc.jpg",
  },
  {
    nombre: "Plato mixto con queso y tocineta",
    descripcion: "Combinación de carnes a la parrilla, cubiertas con queso fundido y tocineta crocante, acompañadas de papas, arepa y ensalada.",
    precio: 45000,
    categoria: "opcional-carnes",
    imagen: "productos_imagenes/comidas/platomixtoqyt.jpg",
  },
  {
    nombre: "Sancocho trifasico",
    descripcion: "Sancocho tradicional con carnes de res, cerdo y pollo, acompañado de arroz, arepa, aguacate y ensalada fresca.",
    precio: 40000,
    categoria: "platos especiales",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767975402/sancochotrifasico_ijtfge.jpg",
  },
  {
    nombre: "Sancocho de pescado",
    descripcion: "Sancocho de pescado preparado con verduras frescas, servido con arroz, arepa y aguacate.",
    precio: 40000,
    categoria: "platos especiales",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767975499/sancochopescado_fr4vro.jpg",
  },
  {
    nombre: "Mondongo",
    descripcion: "Sopa tradicional de mondongo, cocinada a fuego lento con verduras y carnes, acompañada de arroz, arepa y aguacate.",
    precio: 40000,
    categoria: "platos especiales",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767975499/mondongo_rudqtk.jpg",
  },
  {
    nombre: "Picada para dos personas",
    descripcion: "Selección de carnes a la parrilla, chicharrón, chorizo, papas a la francesa, arepas y acompañamientos de la casa, ideal para dos personas.",
    precio: 60000,
    categoria: "picadas",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901526/picadados_klnqhx.jpg",
  },
  {
    nombre: "Picada para cuatro personas",
    descripcion: "Variedad de carnes a la parrilla, chicharrón, chorizo, papas a la francesa, arepas y acompañamientos de la casa, ideal para cuatro personas.",
    precio: 100000,
    categoria: "picadas",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/w_700,q_auto,f_auto/v1767901525/picadacuatro_krrgfj.jpg",
  },
  {
    nombre: "Picada para ocho personas",
    descripcion: "Gran selección de carnes a la parrilla, chicharrón, chorizo, papas a la francesa, arepas y acompañamientos de la casa, ideal para ocho personas.",
    precio: 190000,
    categoria: "picadas",
    imagen: "https://res.cloudinary.com/dvx8yz3sc/image/upload/v1767976416/picadaocho_tdjpzk.jpg",
  },
  {
    nombre: "Corona 330 ml",
    descripcion: "",
    precio: 14300,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/corona330.jpg",
  },
  {
    nombre: "stella artois",
    descripcion: "",
    precio: 14300,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/stella.jpg",
  },
  {
    nombre: "tres cordilleras negra",
    descripcion: "",
    precio: 14300,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/trescornegra.jpg",
  },
  {
    nombre: "tres cordilleras rosada",
    descripcion: "",
    precio: 11900,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/trescorrosada.jpg",
  },
  {
    nombre: "tres cordilleras roja",
    descripcion: "",
    precio: 11900,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/trescorroja.jpg",
  },
  {
    nombre: "tres cordilleras verde",
    descripcion: "",
    precio: 11900,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/trescorverde.jpg",
  },
  {
    nombre: "heineken",
    descripcion: "",
    precio: 11900,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/heineken.jpg",
  },
  {
    nombre: "budweiser lata",
    descripcion: "",
    precio: 8350,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/budweiser.jpg",
  },
  {
    nombre: "aguila original 330 ml",
    descripcion: "",
    precio: 8350,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/aguilaoriginal.jpg",
  },
  {
    nombre: "aguila light 330 ml",
    descripcion: "",
    precio: 8350,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/aguilalight.jpg",
  },
  {
    nombre: "poker 330ml",
    descripcion: "",
    precio: 8350,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/poker330.jpg",
  },
  {
    nombre: "Sol 330ml",
    descripcion: "",
    precio: 11900,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/sol330.jpg",
  },
  {
    nombre: "reeds",
    descripcion: "",
    precio: 8350,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/redds.jpg",
  },
  {
    nombre: "club colombia",
    descripcion: "",
    precio: 8950,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/clubcolombia.jpg",
  },
  {
    nombre: "cola y pola",
    descripcion: "",
    precio: 5950,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/colapola.jpg",
  },
  {
    nombre: "andina 330ml",
    descripcion: "",
    precio: 0,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/andina330.jpg",
  },
  {
    nombre: "jarra refajo",
    descripcion: "",
    precio: 21400,
    categoria: "cervezas",
    imagen: "productos_imagenes/bar-heladeria/jarrarefajo.jpg",
  },
  {
    nombre: "Michelado tradicional",
    descripcion: "",
    precio: 3600,
    categoria: "michelados",
    imagen: "productos_imagenes/bar-heladeria/vasomichelado.jpg",
  },
  {
    nombre: "Michelado - Frutos rojos",
    descripcion: "",
    precio: 3600,
    categoria: "michelados",
    imagen: "productos_imagenes/bar-heladeria/micheladorosa.jpg",
  },
  {
    nombre: "Michelado - Mango",
    descripcion: "",
    precio: 3600,
    categoria: "michelados",
    imagen: "productos_imagenes/bar-heladeria/micheladomango.jpg",
  },
  {
    nombre: "Botella - antioqueño azul",
    descripcion: "",
    precio: 107100*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Media - antioqueño azul",
    descripcion: "",
    precio: 59500*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Botella - antioqueño verde",
    descripcion: "",
    precio: 101150*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Media - antioqueño verde",
    descripcion: "",
    precio: 53550*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Botella amarillo - Real antioqueño",
    descripcion: "",
    precio: 90000*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Botella - Ron medellin 3 años",
    descripcion: "",
    precio: 101150*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Media - Ron medellin 3 años",
    descripcion: "",
    precio: 59500*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Botella - Ron rosado",
    descripcion: "",
    precio: 90000*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Botella - Ron medellin",
    descripcion: "",
    precio: 101150*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Media - Ron medellin",
    descripcion: "",
    precio: 45000*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Botella - Ron caldas",
    descripcion: "",
    precio: 107100*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Media - Ron caldas",
    descripcion: "",
    precio: 59500*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Botella - Brandy",
    descripcion: "",
    precio: 113050*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Media - Brandy",
    descripcion: "",
    precio: 65450*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Botella - Cristal XS < S < L",
    descripcion: "",
    precio: 89250*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Media - Cristal XS < S < L",
    descripcion: "",
    precio: 47600*1.2,
    categoria: "licores - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Gaseosas 250ml",
    descripcion: "",
    precio: 3600,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Gaseosas 350ml",
    descripcion: "",
    precio: 4750,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Gaseosas - Postobon 1.5L ",
    descripcion: "",
    precio: 10700,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Gaseosas - Postobon 2.5L",
    descripcion: "",
    precio: 15500,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Pony malta 330ml",
    descripcion: "",
    precio: 4800,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Pony malta 1L",
    descripcion: "",
    precio: 9500,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Coca cola 350ml",
    descripcion: "",
    precio: 4750,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Coca cola 400ml",
    descripcion: "",
    precio: 5950,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Coca cola 600ml",
    descripcion: "",
    precio: 7100,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Coca cola 1.5L",
    descripcion: "",
    precio: 11900,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Coca cola 2.25L",
    descripcion: "",
    precio: 17850,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "H2O",
    descripcion: "",
    precio: 5950,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Gatorade",
    descripcion: "",
    precio: 7100,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Ginger Pequeña",
    descripcion: "",
    precio: 4800,
    categoria: "bebidas gaseosas",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Torta almohabana",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Festival",
    descripcion: "",
    precio: 3000,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Galleta milo",
    descripcion: "",
    precio: 3000,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Galleta oreo ",
    descripcion: "",
    precio: 3000,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Bocadillo",
    descripcion: "",
    precio: 1000,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Cheetos pequeños",
    descripcion: "",
    precio: 5000,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Choclitos pequeños",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Margarita pequeño",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "DeTodito mediano",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "DeTodito pequeño",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Cheetos grande",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Margarita grande",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Natuchips grande",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Doritos grande",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Choclitos grande",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Chocoso",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Casero pastel",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Brownie",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Submarino",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Pekitas",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Piolo",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Pinguino",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Manimotos",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "DeTodito Grande",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Chokis",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Manchitas",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Natuchips pequeño",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Paleta dracula",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Nucita",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jumbito mini",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Paleta Tosh",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Bocatto",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Casero helado",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Helado artesanal",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Paleta agua",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Chococono",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Polet",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Vaso Aloha",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jet helado",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Lucky Strike x10",
    descripcion: "",
    precio: 11000,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Marlboro x20",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Marlboro x10",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Caribe x20",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Caribe x10",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "LYM x20",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "LYM x10",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Premier x20",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Premier x10",
    descripcion: "",
    precio: 10000,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Bonfiest",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Dolex forte",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Lua",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Aspirina",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Acetaminofen",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Alkasetzer",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Curas",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "candelas",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "chocolores",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "trident cool",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "trident total",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "trident individual",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "adams individual",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "barra halls",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "halls individual",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "bon bon bum",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "bananas",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "club social",
    descripcion: "",
    precio: 0,
    categoria: "dulceria - bar",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Brownie con helado",
    descripcion: "",
    precio: 13000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Banana split",
    descripcion: "",
    precio: 16000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Copa kick",
    descripcion: "",
    precio: 16000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Copa oreo",
    descripcion: "",
    precio: 16000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Copa milo",
    descripcion: "",
    precio: 16000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Ensalada de frutas",
    descripcion: "",
    precio: 17000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Copa coffee delight",
    descripcion: "",
    precio: 17000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Copa frutos rojos",
    descripcion: "",
    precio: 17000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Copa durazno",
    descripcion: "",
    precio: 17000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Copa Baileys",
    descripcion: "",
    precio: 18000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Malteada",
    descripcion: "",
    precio: 12000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Cono una bola",
    descripcion: "",
    precio: 4500,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Cono dos bolas",
    descripcion: "",
    precio: 7000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Torta",
    descripcion: "",
    precio: 7000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Torta cumpleaños",
    descripcion: "",
    precio: 16000,
    categoria: "heladeria",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jarra de limonada natural o panela",
    descripcion: "",
    precio: 17000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jarra de jugo en agua",
    descripcion: "",
    precio: 20000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jarra de jugo en leche",
    descripcion: "",
    precio: 22000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jarra de maracuya en agua",
    descripcion: "",
    precio: 22000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jarra de maracuya en leche",
    descripcion: "",
    precio: 24000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jarra de limonada de coco",
    descripcion: "",
    precio: 24000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Tamarindo michelado",
    descripcion: "",
    precio: 7000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Limonada natural o panela",
    descripcion: "",
    precio: 7000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jugo en agua",
    descripcion: "",
    precio: 8000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jugo en leche",
    descripcion: "",
    precio: 9000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jugo de maracuya en agua",
    descripcion: "",
    precio: 9000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Jugo de maracuya en leche",
    descripcion: "",
    precio: 10000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Limonada de coco",
    descripcion: "",
    precio: 10000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Vaso de leche",
    descripcion: "",
    precio: 2500,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Milo frio",
    descripcion: "",
    precio: 10000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Mazamorra o claro",
    descripcion: "",
    precio: 6000,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Botella de agua con o sin gas",
    descripcion: "",
    precio: 3500,
    categoria: "jugos naturales",
    imagen: "productos_imagenes/bar-heladeria/insertarnombre",
  },
  {
    nombre: "Margarita",
    descripcion: "Tequila, triple sec y limón - FRESA, MARACUYA, CEREZA.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Mojito",
    descripcion: "Ron blanco, yerbabuena, triple sec, azucar, limón, soda - FRESA, MARACUYA, COCO.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Long island iced tea",
    descripcion: "Vodka, triple sec, ron, tequila, gin - COLA, BLUE.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Daiquiri",
    descripcion: "Ron blanco, limon y azucar - FRESA, MARACUYA.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Gin & tonic",
    descripcion: "Gin, selección de tónicas, botánicos y agua tónica.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Piña colada",
    descripcion: "Ron blanco, piña, piña colada, crema de coco.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Camelias coctel",
    descripcion: "Ron añejo, mora, maracuyá, café y tomillo.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "El mirador coctel",
    descripcion: "Ron añejo, piña y maracuyá.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Malibu bay breeze",
    descripcion: "Malibu de coco, cramberry y piña.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Amarulo",
    descripcion: "Aguardiente, lulo y yerbabuena.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "El arriero",
    descripcion: "Vodka, licot de café, Bailey's, helado de vainilla.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Martini lychee",
    descripcion: "Vodka, soho lychee, triple sec.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Cosmopolitan",
    descripcion: "Absolut raspberry, triple sec y cramberry.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Martini fresh",
    descripcion: "Vodka, sauco, pepino.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "High ball",
    descripcion: "Whisky, maracuya, limón, hielo triturado.",
    precio: 0,
    categoria: "cocteles",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Soda saborizada",
    descripcion: "Maracuyá o fresa.",
    precio: 0,
    categoria: "bebidas sin alcohol",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Punch citrico",
    descripcion: "Maracuya, piña, soda y naranja.",
    precio: 0,
    categoria: "bebidas sin alcohol",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Colada tropical",
    descripcion: "Fresa, banano, piña y crema de coco.",
    precio: 0,
    categoria: "bebidas sin alcohol",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Granizados",
    descripcion: "Maracuyá, fresa, mora.",
    precio: 0,
    categoria: "bebidas sin alcohol",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Granizados",
    descripcion: "Café, milo.",
    precio: 0,
    categoria: "bebidas sin alcohol",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Granizado de vino",
    descripcion: "",
    precio: 0,
    categoria: "granizados con alcohol",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Granizado de cafe con baileys",
    descripcion: "",
    precio: 0,
    categoria: "granizados con alcohol",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  // BUCHANAN'S
  {
    nombre: "Botella - Buchanan's",
    descripcion: "",
    precio: 357000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Buchanan's",
    descripcion: "",
    precio: 238000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Buchanan's",
    descripcion: "",
    precio: 35700,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // BUCHANAN'S MASTER
  {
    nombre: "Botella - Buchanan's Master",
    descripcion: "",
    precio: 392700,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // OLD PARR
  {
    nombre: "Botella - Old Parr",
    descripcion: "",
    precio: 357000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Old Parr",
    descripcion: "",
    precio: 238000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },  
  {
    nombre: "Trago - Old Parr",
    descripcion: "",
    precio: 35700,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // JACK DANIEL'S
  {
    nombre: "Botella - Jack Daniel's",
    descripcion: "",
    precio: 357000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Jack Daniel's",
    descripcion: "",
    precio: 238000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Jack Daniel's",
    descripcion: "",
    precio: 30080,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // JACK DANIEL'S HONEY
  {
    nombre: "Botella - Jack Daniel's Honey",
    descripcion: "",
    precio: 357000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Jack Daniel's Honey",
    descripcion: "",
    precio: 238000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // GLENFIDDICH 12
  {
    nombre: "Botella - Glenfiddich 12",
    descripcion: "",
    precio: 321300,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Glenfiddich 12",
    descripcion: "",
    precio: 35700,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // CHIVAS REGAL 12
  {
    nombre: "Botella - Chivas Regal 12",
    descripcion: "",
    precio: 357000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Chivas Regal 12",
    descripcion: "",
    precio: 238000,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Chivas Regal 12",
    descripcion: "",
    precio: 35700,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // CHIVAS REGAL EXTRA
  {
    nombre: "Botella - Chivas Regal Extra",
    descripcion: "",
    precio: 392700,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Chivas Regal Extra",
    descripcion: "",
    precio: 261800,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Chivas Regal Extra",
    descripcion: "",
    precio: 38100,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // CHIVAS REGAL 18
  {
    nombre: "Botella - Chivas Regal 18",
    descripcion: "",
    precio: 452200,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // GRANT'S
  {
    nombre: "Botella - Grant's",
    descripcion: "",
    precio: 202300,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Grant's",
    descripcion: "",
    precio: 130900,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Grant's",
    descripcion: "",
    precio: 33350,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // SOMETHING SPECIAL
  {
    nombre: "Botella - Something Special",
    descripcion: "",
    precio: 202300,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Something Special",
    descripcion: "",
    precio: 107100,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // JOHNNIE WALKER BLACK
  {
    nombre: "Botella - Johnnie Walker Black",
    descripcion: "",
    precio: 309400,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Johnnie Walker Black",
    descripcion: "",
    precio: 190400,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // JOHNNIE WALKER RED
  {
    nombre: "Botella - Johnnie Walker Red",
    descripcion: "",
    precio: 214200,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Johnnie Walker Red",
    descripcion: "",
    precio: 142800,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // PASSPORT
  {
    nombre: "Botella - Passport",
    descripcion: "",
    precio: 154700,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Passport",
    descripcion: "",
    precio: 95200,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // BLACK & WHITE
  {
    nombre: "Botella - Black & White",
    descripcion: "",
    precio: 154700,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Black & White",
    descripcion: "",
    precio: 95200,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // BALLANTINE'S
  {
    nombre: "Botella - Ballantine's",
    descripcion: "",
    precio: 154700,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Media - Ballantine's",
    descripcion: "",
    precio: 95200,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // JAMESON
  {
    nombre: "Botella - Jameson",
    descripcion: "",
    precio: 226100,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },

  // THE GLENLIVET
  {
    nombre: "Botella - The Glenlivet",
    descripcion: "",
    precio: 321300,
    categoria: "whiskys",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Patrón Reposado",
    descripcion: "",
    precio: 476000,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Patrón Añejo",
    descripcion: "",
    precio: 440300,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Patrón Silver",
    descripcion: "",
    precio: 416500,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Don Julio Silver",
    descripcion: "",
    precio: 416500,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Don Julio Añejo",
    descripcion: "",
    precio: 476000,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Don Julio Añejo",
    descripcion: "",
    precio: 440300,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Don Julio 70",
    descripcion: "",
    precio: 595000,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Herradura Plata",
    descripcion: "",
    precio: 380800,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Herradura Reposado",
    descripcion: "",
    precio: 440300,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Altos Olmeca Plata",
    descripcion: "",
    precio: 261800,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Jimador Reposado",
    descripcion: "",
    precio: 249900,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Jimador Reposado",
    descripcion: "",
    precio: 178500,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - 1800 Añejo",
    descripcion: "",
    precio: 392700,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - 1800 Reposado",
    descripcion: "",
    precio: 416500,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Leyenda del Milagro",
    descripcion: "",
    precio: 297500,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Mezcal Contraluz (Maluma)",
    descripcion: "",
    precio: 595000,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - José Cuervo Reposado",
    descripcion: "",
    precio: 190400,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - José Cuervo Reposado",
    descripcion: "",
    precio: 107100,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Olmeca Reposado",
    descripcion: "",
    precio: 178500,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Tequila (José Cuervo)",
    descripcion: "",
    precio: 23800,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Jimador Cristalino",
    descripcion: "",
    precio: 273300,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Jimador Cristalino",
    descripcion: "",
    precio: 178500,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Tequila (Jimador)",
    descripcion: "",
    precio: 29750,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Maestro Dobel Diamante",
    descripcion: "",
    precio: 430000,
    categoria: "tequilas",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Viejo 15 Años",
    descripcion: "",
    precio: 261800,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Viejo 8 Años",
    descripcion: "",
    precio: 202300,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Ron Viejo 8 Años",
    descripcion: "",
    precio: 107100,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Viejo 5 Años",
    descripcion: "",
    precio: 130900,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Ron Viejo 5 Años",
    descripcion: "",
    precio: 71400,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Ron 3 Años",
    descripcion: "",
    precio: 10750,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Parce 8 Años",
    descripcion: "",
    precio: 357000,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Parce 12 Años",
    descripcion: "",
    precio: 416500,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Bacardí Limón",
    descripcion: "",
    precio: 178500,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Havana Club 3 Años",
    descripcion: "",
    precio: 154700,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Havana Club 7 Años",
    descripcion: "",
    precio: 214200,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Barceló",
    descripcion: "",
    precio: 214200,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Ron Cheers",
    descripcion: "",
    precio: 142800,
    categoria: "ron",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Gray Goose",
    descripcion: "",
    precio: 357000,
    categoria: "vodka",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Reyka",
    descripcion: "",
    precio: 273700,
    categoria: "vodka",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Absolut (Raspberry-Mandarin)",
    descripcion: "",
    precio: 202300,
    categoria: "vodka",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Absolut (Raspberry-Mandarin)",
    descripcion: "",
    precio: 107100,
    categoria: "vodka",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Absolut (Raspberry-Mandarin)",
    descripcion: "",
    precio: 21450,
    categoria: "vodka",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Smirnoff",
    descripcion: "",
    precio: 154700,
    categoria: "vodka",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Smirnoff",
    descripcion: "",
    precio: 107100,
    categoria: "vodka",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Smirnoff Lulo",
    descripcion: "",
    precio: 107100,
    categoria: "vodka",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Smirnoff Lulo",
    descripcion: "",
    precio: 59500,
    categoria: "vodka",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Disaronno Amaretto",
    descripcion: "",
    precio: 237700,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Bailey's",
    descripcion: "",
    precio: 178500,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Bailey's",
    descripcion: "",
    precio: 107100,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Bailey's",
    descripcion: "",
    precio: 17850,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Dubonnet",
    descripcion: "",
    precio: 142800,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Beefeater Dry",
    descripcion: "",
    precio: 238000,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Beefeater Pink",
    descripcion: "",
    precio: 261800,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Gordon's Pink",
    descripcion: "",
    precio: 190400,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Gordon's",
    descripcion: "",
    precio: 166500,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Hendrick's",
    descripcion: "",
    precio: 452200,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Hendrick's",
    descripcion: "",
    precio: 41650,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Monkey 47",
    descripcion: "",
    precio: 416500,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Jagermeister",
    descripcion: "",
    precio: 238000,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Jagermeister",
    descripcion: "",
    precio: 35700,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Aguardiente Amarillo",
    descripcion: "",
    precio: 107100,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Aguardiente Amarillo",
    descripcion: "",
    precio: 59500,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Trago - Aguardiente Amarillo",
    descripcion: "",
    precio: 9550,
    categoria: "licores",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Sangre de Toro Original",
    descripcion: "",
    precio: 190400,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Sangre de Toro Reserva",
    descripcion: "",
    precio: 226100,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Gato Negro Merlot",
    descripcion: "",
    precio: 119000,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Gato Negro Merlot",
    descripcion: "",
    precio: 71400,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Gato Negro Cabernet",
    descripcion: "",
    precio: 119000,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Gato Negro Cabernet",
    descripcion: "",
    precio: 71400,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Piccolo - Gato Negro Cabernet",
    descripcion: "",
    precio: 23800,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Gato Negro Vino Blanco",
    descripcion: "",
    precio: 119000,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Gato Negro Vino Blanco",
    descripcion: "",
    precio: 71400,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Casillero del Diablo Merlot",
    descripcion: "",
    precio: 166600,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Casillero del Diablo Cabernet",
    descripcion: "",
    precio: 178500,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Medio - Casillero del Diablo Cabernet",
    descripcion: "",
    precio: 95200,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Lambrusco Rosso",
    descripcion: "",
    precio: 83300,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Lambrusco Tinto",
    descripcion: "",
    precio: 83300,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Frontera Merlot",
    descripcion: "",
    precio: 119900,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Frontera Cabernet",
    descripcion: "",
    precio: 119900,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - La Huerta Merlot",
    descripcion: "",
    precio: 83300,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - La Huerta Rosé",
    descripcion: "",
    precio: 83300,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - La Huerta Cabernet",
    descripcion: "",
    precio: 83300,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Marqués de Casa Concha",
    descripcion: "",
    precio: 261800,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Cono Sur Bicicleta Reserva",
    descripcion: "",
    precio: 107100,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Reserva",
    descripcion: "",
    precio: 95200,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Sangría",
    descripcion: "",
    precio: 95200,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella - Sangría Especial",
    descripcion: "",
    precio: 119900,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Copa - Sangría",
    descripcion: "",
    precio: 33300,
    categoria: "vinos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "La Huerta Vino Blanco",
    descripcion: "",
    precio: 83300,
    categoria: "vino blanco",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Gato Negro Vino Blanco",
    descripcion: "",
    precio: 119000,
    categoria: "vino blanco",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Viña Esmeralda",
    descripcion: "",
    precio: 175800,
    categoria: "vino blanco",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Woodbridge Chardonnay",
    descripcion: "",
    precio: 202300,
    categoria: "vino blanco",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Valdivieso Rosé",
    descripcion: "",
    precio: 154700,
    categoria: "espumosos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Chandon Rosé",
    descripcion: "",
    precio: 190400,
    categoria: "espumosos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "JP Rosado y Blanco",
    descripcion: "",
    precio: 20230,
    categoria: "espumosos",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Café",
    descripcion: "",
    precio: 4200,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Café Expresso",
    descripcion: "",
    precio: 6550,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Café Americano",
    descripcion: "",
    precio: 6550,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Café Leche",
    descripcion: "",
    precio: 7150,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Capuccino",
    descripcion: "",
    precio: 8950,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Mocaccino",
    descripcion: "",
    precio: 9550,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Carajillo (Ron, aguardiente)",
    descripcion: "",
    precio: 16700,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Vaso de Leche",
    descripcion: "",
    precio: 3000,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Capuccino Bailey's",
    descripcion: "",
    precio: 16700,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Maizena Tradicional",
    descripcion: "",
    precio: 9550,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Maizena Sabores",
    descripcion: "",
    precio: 10750,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Maizena Bailey's",
    descripcion: "",
    precio: 17850,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Aromática",
    descripcion: "",
    precio: 5950,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Aromática Frutos Rojos",
    descripcion: "",
    precio: 5950,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Milo Caliente",
    descripcion: "",
    precio: 8350,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Milo Frío",
    descripcion: "",
    precio: 11900,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Granizado de Café",
    descripcion: "",
    precio: 11900,
    categoria: "bebidas calientes - cafe",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella de Agua",
    descripcion: "",
    precio: 3600,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella Agua Gas",
    descripcion: "",
    precio: 3600,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Botella de Agua Pequeña",
    descripcion: "",
    precio: 2400,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Vive 100 Mediano",
    descripcion: "",
    precio: 4200,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Vive 100 Pequeño",
    descripcion: "",
    precio: 3600,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Savilor Grande",
    descripcion: "",
    precio: 3600,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Gatorade",
    descripcion: "",
    precio: 7150,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Electrolit",
    descripcion: "",
    precio: 16650,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Smirnoff Ice",
    descripcion: "",
    precio: 16650,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "JP Lata Rosado y Blanco",
    descripcion: "",
    precio: 20230,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Four Loko",
    descripcion: "",
    precio: 26200,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Soda (Bretaña)",
    descripcion: "",
    precio: 4750,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Spartan Pequeño",
    descripcion: "",
    precio: 3000,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Red Bull",
    descripcion: "",
    precio: 14300,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Monster",
    descripcion: "",
    precio: 16650,
    categoria: "embotellados - cocteleria",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Vasos Escarchados (Sal y Limón)",
    descripcion: "",
    precio: 3600,
    categoria: "adicionales",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Porción de Maní",
    descripcion: "",
    precio: 3600,
    categoria: "adicionales",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Jarra de Soda",
    descripcion: "",
    precio: 14300,
    categoria: "pasantes",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  {
    nombre: "Jarra de Agua con Limón",
    descripcion: "",
    precio: 7150,
    categoria: "pasantes",
    imagen: "productos_imagenes/cocteleria/insertarnombre",
  },
  
]

/* ===============================
   2. REFERENCIAS DOM
================================ */

const menuContainer = document.getElementById("menu");
const categoryButtons = document.querySelectorAll(".category-btn");


/* ===============================
   3. RENDER DEL MENÚ
================================ */

function renderMenu(items) {
  menuContainer.innerHTML = "";

  if (!items || items.length === 0) {
    menuContainer.innerHTML = "<p>No hay productos disponibles</p>";
    return;
  }

  items.forEach(item => {
    const card = document.createElement("div");
    card.className = "menu-card";

    // Imagen
    if (item.imagen) {
      const img = document.createElement("img");
      img.src = item.imagen;
      img.alt = item.nombre;

      img.onerror = () => {
        img.style.display = "none";
      };

      card.appendChild(img);
    }

    // Información
    const info = document.createElement("div");
    info.className = "menu-card-content";

    info.innerHTML = `
      <h3>${item.nombre}</h3>
      ${item.descripcion ? `<p>${item.descripcion}</p>` : ""}
      <span class="price">$${item.precio.toLocaleString("es-CO")}</span>
    `;

    card.appendChild(info);
    menuContainer.appendChild(card);
  });
}


/* ===============================
   4. FILTRO POR CATEGORÍAS
================================ */

categoryButtons.forEach(btn => {
  btn.addEventListener("click", () => {
    const categoria = btn.dataset.category;

    // Botón activo
    categoryButtons.forEach(b => b.classList.remove("active"));
    btn.classList.add("active");

    // Filtrar productos
    const filtrados = menuItems.filter(
      item => item.categoria === categoria
    );

    renderMenu(filtrados);
  });
});


/* ===============================
   5. RENDER INICIAL (PORCIONES)
================================ */

const categoriaInicial = "porciones";

// Marcar botón activo inicial
categoryButtons.forEach(btn => {
  if (btn.dataset.category === categoriaInicial) {
    btn.classList.add("active");
  }
});

// Render inicial optimizado
const productosIniciales = menuItems.filter(
  item => item.categoria === categoriaInicial
);

renderMenu(productosIniciales);
